# This file was generated by GoReleaser. DO NOT EDIT.
cask "kazi" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "77cb05dcf1d26381deef6432434a36d988a3d5d26cdd52d34d0b48c4f596e6cd"
      url "https://github.com/thapakazi/kazi/releases/download/v#{version}/kazi_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "62b13ebd1d8bbcbf51d8470b75b4bdf44d148fecf8d9dca89d8a15f2d99d3a81"
      url "https://github.com/thapakazi/kazi/releases/download/v#{version}/kazi_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d82ca52716aaf749ef325aef823d72fd41323d9e85fe24a462572c1abbccbc62"
      url "https://github.com/thapakazi/kazi/releases/download/v#{version}/kazi_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "db107409f8f184cc3d9a07eb778785aca2bbadb62df943522faf629995fa548d"
      url "https://github.com/thapakazi/kazi/releases/download/v#{version}/kazi_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kazi"
  desc "The control plane for your local containers"
  homepage "https://thapakazi.github.io/kazi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kazi"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kazi"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kazi needs a container runtime with compose support on your PATH
    (Docker is first-class; podman and nerdctl are auto-detected).
  EOS
end
