# This file was generated by GoReleaser. DO NOT EDIT.
cask "kazi" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "cd5bc8d7ef35c6ce8c0642c298290378286fd4606123b1401eebab4e0cb9414c"
      url "https://github.com/thapakazi/kazi/releases/download/v#{version}/kazi_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3ab21b6fbb73b61f860783219004e69ff6e4c3c77d5d43661a013b7832df3764"
      url "https://github.com/thapakazi/kazi/releases/download/v#{version}/kazi_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1c5503755b4228b23bb70cebb98dc37027dc5e7a81dbe5b05cf943311b966400"
      url "https://github.com/thapakazi/kazi/releases/download/v#{version}/kazi_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "eae110f2dec7fcdfde5ed663057e0eff43a942d79cf0cb34388f43f3db867f19"
      url "https://github.com/thapakazi/kazi/releases/download/v#{version}/kazi_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kazi"
  desc "The control plane for your local containers"
  homepage "https://thapakazi.github.io/kazi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kazi"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kazi"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    kazi needs a container runtime with compose support on your PATH
    (Docker is first-class; podman and nerdctl are auto-detected).
  EOS
end
